### ISSUE TITLE
rust-crypto is abandoned

### ISSUE THREAD

**Issue by untitaker** [untitaker/mysteryshack#39]
- [ ] https://github.com/Keats/rust-jwt/issues/7

Other issues reported: https://github.com/inejge/pwhash/issues/2

**Comment by untitaker** [comment]
https://github.com/Keats/rust-jwt/issues/7

**Comment by untitaker** [comment]
https://github.com/inejge/pwhash/issues/2

**Comment by untitaker** [comment]
https://github.com/untitaker/mysteryshack/commit/0abb67db20e4bee11a203cf817ef210e22e477dd replaces direct use of rust-crypto with libsodium

**Comment by DaGenix** [comment]
Rust-Crypto isn't abandoned, but it has been badly ignored and for that I apologize.

That being said, Rust-Crypto is still very experimental and has not had anything resembling the amount of security review of something like libsodium. If security is important to you, there are good reasons you might want to consider using that library anyway.

**Comment by untitaker** [comment]
I guess I'll close this then. Thanks for the response.
