### ISSUE TITLE
Running outside release

### ISSUE THREAD

**Issue by hmrodrigues** [untitaker/mysteryshack#63]
Hey,
So I'm having a problem, even after adding _./target/release_ to path, when I run mysteryshack serve it gives os error 2, but if I run inside the release directory works.
`Failed to parse config: No such file or directory (os error 2)`

My idea is that mysteryshack doesn't find the configuration file, wouldn't be better to have the config file in some common place (like ~/.mysteryshack) ou add a flag to load the file
`mysterysharck serve -c path/to/config`

**Comment by untitaker** [comment]
That exact flag exists, but you have to put it before the `serve` command as it's a global option and not specific to `serve`.

Where is your config? It should be in the current working directory, otherwise you indeed have to use `-c`.

**Comment by hmrodrigues** [comment]
Oh I totally missed it hahaha
It's in the release folder.
