### ISSUE TITLE
I can use laverna to connect my own server

### ISSUE THREAD

**Issue by C1tas** [untitaker/mysteryshack#70]
the output
Server error: IronError { error: NoRoute, response: HTTP/1.1 404 Not Found
Content-Type: text/html; charset=utf-8
Content-Length: 1559
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: DENY
Content-Security-Policy: default-src 'self';frame-ancestors 'none'

 }

**Comment by untitaker** [comment]
Please update mysteryshack (git pull && make).

**Comment by C1tas** [comment]
ok, i'll try

**Comment by C1tas** [comment]
i got some error massage on laverna.cc , 

does it means  i need https?

```
Blocked loading mixed active content “http://c1tas.com:6767/.well-known/webfinger?resource=acct:r7@c1tas.com:6767”[Learn More]  remotestorage.js:459:1622
Blocked loading mixed active content “http://c1tas.com:6767/.well-known/host-meta?resource=acct:r7@c1tas.com:6767”[Learn More]  remotestorage.js:459:1622
Blocked loading mixed active content “http://c1tas.com:6767/.well-known/host-meta.json?resource=acct:r7@c1tas.com:6767”[Learn More]  remotestorage.js:459:1622
Discovery failed Object { message: "Failed to contact storage server.", stack: "" } "Failed to contact storage server."  remotestorage.js:460:388
Discovery failed Object { message: "No storage information found at tha…", stack: "" } "No storage information found at that user address."  remotestorage.js:460:388
```

**Comment by untitaker** [comment]
Yes you do need https.

**Comment by C1tas** [comment]
ok,thanks a lot

**Comment by C1tas** [comment]
when i use nginx Reverse Proxy for https
and i get i new issuse
when i login 

The page response
CSRF detected.

you can hava a test on https://rs.c1tas.com

**Comment by untitaker** [comment]
You need to configure proxy headers.

**Comment by C1tas** [comment]
the nginx proxy header? or in `config` file

Thanks for your patient：D

**Comment by untitaker** [comment]
Which headers you need to set is explained in
https://github.com/untitaker/mysteryshack/blob/master/config.example

So for reverse proxying, enable `use_proxy_headers` and set the headers from
the config file in your nginx configuration file.

**Comment by C1tas** [comment]
i get the massage on my chrome console
```
https://rs.c1tas.com/.well-known/webfinger?resource=acct:r7@rs.c1tas.com:443 Failed to load resource: the server responded with a status of 404 (Not Found)
XMLHttpRequest cannot load https://rs.c1tas.com/.well-known/webfinger?resource=acct:r7@rs.c1tas.com:443. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://laverna.cc' is therefore not allowed access. The response had HTTP status code 404.
```

the Access-Control-Allow-Origin i have already add into my ngnix config


i use Let’s Encrypt to get https

there is a part of my config
```
proxy_pass http://127.0.0.1:6767
proxy_set_header Host $host:80;
proxy_set_header X-Real_IP $remote_addr;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Server $host;
proxy_set_header X-Forwarded-Port $server_port;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme
add_header Access_Control-Allow-Origin *;




#ACME challenge
location ^~ /.well-known {
      allow all;
      alias /var/lib/letsencrypt/.well-known/;
      default_type "text/plain";
      try_files $uri = 404;
} 
```

i found that i don't hava webfinger
how can i get it?

**Comment by untitaker** [comment]
Remove the last line 

On 21 March 2017 02:25:18 CET, C1tas <notifications@github.com> wrote:
>i get the massage on my chrome console
>```
>https://rs.c1tas.com/.well-known/webfinger?resource=acct:r7@rs.c1tas.com:443
>Failed to load resource: the server responded with a status of 404 (Not
>Found)
>XMLHttpRequest cannot load
>https://rs.c1tas.com/.well-known/webfinger?resource=acct:r7@rs.c1tas.com:443.
>No 'Access-Control-Allow-Origin' header is present on the requested
>resource. Origin 'https://laverna.cc' is therefore not allowed access.
>The response had HTTP status code 404.
>```
>
>the Access-Control-Allow-Origin i have already add into my ngnix config
>
>there is a part of my config
>```
>proxy_pass http://127.0.0.1:6767
>proxy_set_header Host $host:80;
>proxy_set_header X-Real_IP $remote_addr;
>proxy_set_header X-Forwarded-Host $host;
>proxy_set_header X-Forwarded-Server $host;
>proxy_set_header X-Forwarded-Port $server_port;
>proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>proxy_set_header X-Forwarded-Proto $scheme
>add_header Access_Control-Allow-Origin *;
>```
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/mysteryshack/issues/70#issuecomment-287948722

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by C1tas** [comment]
ok i get it.
but when i click allow
then return to laverna

when in OAuth request page
```
Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-GGH8/O46hXRev+ihzuu7s83VM2VndM2YOXt/9cKjM0g='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

rs.c1tas.com/:23 Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-mgWlZvkLTuhIZ5ZvhD2T0AN91JsWHQiWVXpEx7UkZQ8='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
```

it notice

```
Unauthorized
```


in console
```
GET https://rs.c1tas.com/storage/r7/laverna/ 403 (Forbidden)
remotestorage.js:476 [Sync] Error i.Unauthorized {}
(anonymous) @ remotestorage.js:476
rs.c1tas.com/storage/r7/laverna/notes-db/notes/:1 GET https://rs.c1tas.com/storage/r7/laverna/notes-db/notes/ 403 (Forbidden)
remotestorage.js:476 [Sync] Error i.Unauthorized {}
```


at last when i refresh the page some time 
it works ~
so i think there is some little problem about it authorizing

**Comment by untitaker** [comment]
I also have issues with laverna, but I don't see a 403.
