### ISSUE TITLE
Deploy To Heroku Button

### ISSUE THREAD

**Issue by spencerthayer** [untitaker/mysteryshack#71]
It would be super useful if we could get a `Deploy to Heroku` button which would enable users to easily deploy your software to a Heroku instance without ever leaving the web browser. And with just a little configuration on the users end they'll have something running almost instantly. I propose the button because it is ideal for communities who need to make decisions quickly with the flexibility of something like Heroku.

It's very simple to do, just make sure that an app.json file is located in the repo root directory. More about Heroku deploy buttons [here](https://devcenter.heroku.com/articles/heroku-button).

[![Deploy](https://www.herokucdn.com/deploy/button.png)](https://heroku.com/deploy?template=https://github.com/untitaker/mysteryshack)

**Comment by untitaker** [comment]
I will not advertize a particular hosting service.

On 26 June 2017 17:48:35 GMT+02:00, Spencer Thayer <notifications@github.com> wrote:
>It would be super useful if we could get a `Deploy to Heroku` button
>which would enable users to easily deploy your software to a Heroku
>instance without ever leaving the web browser. And with just a little
>configuration on the users end they'll have something running almost
>instantly. I propose the button because it is ideal for communities who
>need to make decisions quickly with the flexibility of something like
>Heroku.
>
>It's very simple to do, just make sure that an app.json file is located
>in the repo root directory. More about Heroku deploy buttons
>[here](https://devcenter.heroku.com/articles/heroku-button).
>
>[![Deploy](https://www.herokucdn.com/deploy/button.png)](https://heroku.com/deploy?template=https://github.com/untitaker/mysteryshack)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/mysteryshack/issues/71

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
